import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";

/**
 * Setup wizard (Roadmap Phase 7). Guides a new installation to a valid
 * `.env`: parses an existing file to preserve values, prompts for missing
 * required settings, and validates before writing. Pure helpers are
 * exported for tests; the interactive layer stays thin.
 */

export interface SetupAnswers {
  redisUrl: string;
  linearApiKey: string;
  linearWebhookSecret: string;
  dashscopeApiKey: string;
  anthropicApiKey: string;
  openrouterApiKey: string;
  projectsDir: string;
  worktreesDir: string;
  port: string;
}

export function defaultAnswers(): SetupAnswers {
  return {
    redisUrl: "redis://localhost:6379",
    linearApiKey: "",
    linearWebhookSecret: "",
    dashscopeApiKey: "",
    anthropicApiKey: "",
    openrouterApiKey: "",
    projectsDir: "/srv/apps",
    worktreesDir: "/srv/nightforge/worktrees",
    port: "3000",
  };
}

export function parseEnvFile(content: string): Record<string, string> {
  const values: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (trimmed === "" || trimmed.startsWith("#")) {
      continue;
    }
    const separator = trimmed.indexOf("=");
    if (separator <= 0) {
      continue;
    }
    const key = trimmed.slice(0, separator).trim();
    values[key] = trimmed.slice(separator + 1).trim();
  }
  return values;
}

const ANSWER_TO_ENV: Record<keyof SetupAnswers, string> = {
  redisUrl: "REDIS_URL",
  linearApiKey: "LINEAR_API_KEY",
  linearWebhookSecret: "LINEAR_WEBHOOK_SECRET",
  dashscopeApiKey: "DASHSCOPE_API_KEY",
  anthropicApiKey: "ANTHROPIC_API_KEY",
  openrouterApiKey: "OPENROUTER_API_KEY",
  projectsDir: "PROJECTS_DIR",
  worktreesDir: "WORKTREES_DIR",
  port: "PORT",
};

const ENV_TO_ANSWER: Record<string, keyof SetupAnswers> = Object.fromEntries(
  (Object.keys(ANSWER_TO_ENV) as Array<keyof SetupAnswers>).map(
    (answerKey): [string, keyof SetupAnswers] => [ANSWER_TO_ENV[answerKey], answerKey]
  )
);

export function mergeExisting(answers: SetupAnswers, existing: Record<string, string>): SetupAnswers {
  const merged = { ...answers };
  for (const [envKey, value] of Object.entries(existing)) {
    if (value !== "" && envKey in ENV_TO_ANSWER) {
      merged[ENV_TO_ANSWER[envKey]] = value;
    }
  }
  return merged;
}

export function renderEnvFile(answers: SetupAnswers): string {
  const lines = [
    "# Generated by the Nightforge setup wizard",
    `REDIS_URL=${answers.redisUrl}`,
    `LINEAR_API_KEY=${answers.linearApiKey}`,
    `LINEAR_WEBHOOK_SECRET=${answers.linearWebhookSecret}`,
    `DASHSCOPE_API_KEY=${answers.dashscopeApiKey}`,
    `ANTHROPIC_API_KEY=${answers.anthropicApiKey}`,
    `OPENROUTER_API_KEY=${answers.openrouterApiKey}`,
    `PROJECTS_DIR=${answers.projectsDir}`,
    `WORKTREES_DIR=${answers.worktreesDir}`,
    `PORT=${answers.port}`,
  ];
  return `${lines.join("\n")}\n`;
}

export function validateAnswers(answers: SetupAnswers): string[] {
  const errors: string[] = [];
  if (answers.linearApiKey.trim() === "") {
    errors.push("LINEAR_API_KEY is required");
  }
  if (answers.linearWebhookSecret.trim() === "") {
    errors.push("LINEAR_WEBHOOK_SECRET is required");
  }
  const providers = [answers.dashscopeApiKey, answers.anthropicApiKey, answers.openrouterApiKey];
  if (providers.every((key) => key.trim() === "")) {
    errors.push("At least one provider key (DASHSCOPE/ANTHROPIC/OPENROUTER) is required");
  }
  if (!/^\d+$/.test(answers.port)) {
    errors.push("PORT must be a number");
  }
  return errors;
}

interface PromptSpec {
  key: keyof SetupAnswers;
  label: string;
  required: boolean;
}

const PROMPTS: PromptSpec[] = [
  { key: "linearApiKey", label: "Linear API key", required: true },
  { key: "linearWebhookSecret", label: "Linear webhook secret", required: true },
  { key: "dashscopeApiKey", label: "DashScope API key (optional)", required: false },
  { key: "anthropicApiKey", label: "Anthropic API key (optional)", required: false },
  { key: "openrouterApiKey", label: "OpenRouter API key (optional)", required: false },
];

export async function runSetupWizard(targetPath = ".env", force = false): Promise<number> {
  const existing = existsSync(targetPath) ? parseEnvFile(readFileSync(targetPath, "utf8")) : {};
  if (existsSync(targetPath) && !force) {
    console.log(`${targetPath} already exists. Re-run with --force to overwrite.`);
    return 1;
  }

  let answers = mergeExisting(defaultAnswers(), existing);
  const interactive = process.stdin.isTTY;

  if (interactive) {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    const ask = (question: string): Promise<string> =>
      new Promise((resolve) => {
        rl.question(question, (answer) => {
          resolve(answer.trim());
        });
      });
    answers = { ...answers };
    for (const prompt of PROMPTS) {
      if (answers[prompt.key] !== "") {
        continue;
      }
      const answer = await ask(`${prompt.label}: `);
      if (answer !== "") {
        answers[prompt.key] = answer;
      }
    }
    rl.close();
  }

  const errors = validateAnswers(answers);
  if (errors.length > 0) {
    for (const error of errors) {
      console.log(`[missing] ${error}`);
    }
    console.log(interactive ? "Setup incomplete — nothing was written." : "Non-interactive run: edit the values and re-run with --force.");
    return 1;
  }

  writeFileSync(targetPath, renderEnvFile(answers));
  console.log(`Wrote ${targetPath}. Next: npm run diagnostics`);
  return 0;
}

const invokedDirectly = process.argv[1].endsWith("setup-wizard.ts");
if (invokedDirectly) {
  void runSetupWizard(".env", process.argv.includes("--force")).then((code) => {
    process.exitCode = code;
  });
}
